export interface Ping {
  name: string;
  img: string;
  seasonIdx: number;
  type: string;
  line: string;
  gender: string;
  item: string;
  skill: string;
  like: string;
  hate: string;
  romi?: string;
  youtube: string;
}

export interface Season {
  seasonIdx: number;
  name: string;
  color: string;
  filterKey: string;
}

export const colors: { [key: string]: string } = {
  first: "#FF69B4",
  second: "#90E7FE",
  third: "#E44C59",
  fourth: "#E1A5E6",
  fifth: "#666CD7",
  royal: "#fb923c",
  legend: "#7c3aed",
  normal: "#16a34a",
  villain: "#334155",
};

export const pingTypeData: { [key: string]: string } = {
  normal: "일반",
  royal: "로열",
  legend: "레전드",
  villain: "빌런",
};

export const seasonData: Season[] = [
  {
    seasonIdx: 1,
    name: "1기(큐브)",
    color: colors.first,
    filterKey: "first",
  },
  {
    seasonIdx: 2,
    name: "2기(보석)",
    color: colors.second,
    filterKey: "second",
  },
  {
    seasonIdx: 3,
    name: "3기(열쇠)",
    color: colors.third,
    filterKey: "third",
  },
  {
    seasonIdx: 4,
    name: "4기(디저트)",
    color: colors.fourth,
    filterKey: "fourth",
  },
  {
    seasonIdx: 5,
    name: "5기(스타)",
    color: colors.fifth,
    filterKey: "fifth",
  },
];

export const pingData: { [key: string]: Ping[] } = {
  first: [
    {
      name: "하츄핑",
      img: "hachu",
      seasonIdx: 0,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "바로핑",
      img: "baro",
      seasonIdx: 0,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "아자핑",
      img: "aja",
      seasonIdx: 0,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "차차핑",
      img: "chacha",
      seasonIdx: 0,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "라라핑",
      img: "rara",
      seasonIdx: 0,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "해핑",
      img: "hae",
      seasonIdx: 0,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "악동핑",
      img: "akdong",
      seasonIdx: 0,
      type: "villain",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "앙대핑",
      img: "angdae",
      seasonIdx: 0,
      type: "villain",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "키키핑",
      img: "kiki",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "아잉핑",
      img: "aing",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "부끄핑",
      img: "bouque",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "부투핑",
      img: "butu",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "깜빡핑",
      img: "ggambbak",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "띠용핑",
      img: "ddiyong",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "주르핑",
      img: "jur",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "차나핑",
      img: "chana",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "따라핑",
      img: "ddara",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "나르핑",
      img: "nar",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "무셔핑",
      img: "musheo",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "투투핑",
      img: "tutu",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "차캐핑",
      img: "chakae",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "떠벌핑",
      img: "ddeobeol",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "다조핑",
      img: "dajo",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "화나핑",
      img: "hwana",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "시러핑",
      img: "shireo",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "바네핑",
      img: "bane",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "덜덜핑",
      img: "deoldeol",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "그림핑",
      img: "grim",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "무거핑",
      img: "mugeo",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "꺼꿀핑",
      img: "ggeoggul",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "씽씽핑",
      img: "ssingssing",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "베베핑",
      img: "bebe",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "코자핑",
      img: "koja",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "딱풀핑",
      img: "ddakpul",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "모야핑",
      img: "moya",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "토이핑",
      img: "toy",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "또까핑",
      img: "ddogga",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "플라핑",
      img: "fla",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "노라핑&노리핑",
      img: "noranori",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "아휴핑",
      img: "ahew",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "똑똑핑",
      img: "ddokddok",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "꽁꽁핑",
      img: "ggonggong",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "찌릿핑",
      img: "zzirit",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "홀로핑",
      img: "holo",
      seasonIdx: 0,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
  ],
  second: [
    {
      name: "다이아 하츄핑",
      img: "diahachu",
      seasonIdx: 1,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "조아핑",
      img: "joa",
      seasonIdx: 1,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "방글핑",
      img: "bangle",
      seasonIdx: 1,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "믿어핑",
      img: "miteo",
      seasonIdx: 1,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "가면핑",
      img: "gamyeon",
      seasonIdx: 1,
      type: "villain",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "다해핑",
      img: "dahae",
      seasonIdx: 1,
      type: "villain",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "까르핑",
      img: "ggar",
      seasonIdx: 1,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>
눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.
<평화의 크리스탈>
단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "아야핑",
      img: "aya",
      seasonIdx: 1,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>
눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.
<평화의 크리스탈>
단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "소원핑",
      img: "sowon",
      seasonIdx: 1,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>
눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.
<평화의 크리스탈>
단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "토닥핑",
      img: "todak",
      seasonIdx: 1,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>
눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.
<평화의 크리스탈>
단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "쪼꼼핑",
      img: "zzoggom",
      seasonIdx: 1,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>
눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.
<평화의 크리스탈>
단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "싹싹핑",
      img: "ssakssak",
      seasonIdx: 1,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>
눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.
<평화의 크리스탈>
단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "맛나핑",
      img: "matna",
      seasonIdx: 1,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>
눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.
<평화의 크리스탈>
단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "포근핑",
      img: "pogeun",
      seasonIdx: 1,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>
눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.
<평화의 크리스탈>
단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "메모핑",
      img: "memo",
      seasonIdx: 1,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>
눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.
<평화의 크리스탈>
단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "공쥬핑",
      img: "gongzu",
      seasonIdx: 1,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>
눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.
<평화의 크리스탈>
단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "짝짝핑",
      img: "zzakzzak",
      seasonIdx: 1,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>
눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.
<평화의 크리스탈>
단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "주네핑",
      img: "june",
      seasonIdx: 1,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>
눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.
<평화의 크리스탈>
단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "뚝딱핑",
      img: "ddukddak",
      seasonIdx: 1,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>
눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.
<평화의 크리스탈>
단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "발레핑",
      img: "ballet",
      seasonIdx: 1,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>
눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.
<평화의 크리스탈>
단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "원더핑",
      img: "wonder",
      seasonIdx: 1,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>
눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.
<평화의 크리스탈>
단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
  ],
  third: [
    {
      name: "플로라 하츄핑",
      img: "florahachu",
      seasonIdx: 2,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "꾸래핑",
      img: "ggurae",
      seasonIdx: 2,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "나나핑",
      img: "nana",
      seasonIdx: 2,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "솔찌핑",
      img: "solzzi",
      seasonIdx: 2,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "행운핑",
      img: "haengwoon",
      seasonIdx: 2,
      type: "legend",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "빨리핑",
      img: "bbalri",
      seasonIdx: 2,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "얌얌핑",
      img: "yamyam",
      seasonIdx: 2,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "뜨거핑",
      img: "ddgeo",
      seasonIdx: 2,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "삐뽀핑",
      img: "bbibbo",
      seasonIdx: 2,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "간호핑",
      img: "ganho",
      seasonIdx: 2,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "힘내핑",
      img: "himnae",
      seasonIdx: 2,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "고쳐핑",
      img: "gocheo",
      seasonIdx: 2,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "아라핑",
      img: "ara",
      seasonIdx: 2,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "패션핑",
      img: "fashion",
      seasonIdx: 2,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "꼼딱핑",
      img: "ggomddak",
      seasonIdx: 2,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "퐁당핑",
      img: "pongdang",
      seasonIdx: 2,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "파티핑",
      img: "party",
      seasonIdx: 2,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "꾸며핑",
      img: "ggumyeo",
      seasonIdx: 2,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "삐짐핑",
      img: "bbijim",
      seasonIdx: 2,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "아아핑",
      img: "ahah",
      seasonIdx: 2,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "빙글핑",
      img: "bingle",
      seasonIdx: 2,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
  ],
  fourth: [
    {
      name: "베리 하츄핑",
      img: "berryhachu",
      seasonIdx: 3,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "포실핑",
      img: "posil",
      seasonIdx: 3,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "말랑핑",
      img: "mallang",
      seasonIdx: 3,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "샤샤핑",
      img: "shasha",
      seasonIdx: 3,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "새콤핑",
      img: "saekom",
      seasonIdx: 3,
      type: "legend",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "달콤핑",
      img: "dalkom",
      seasonIdx: 3,
      type: "legend",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "뿌뿌핑",
      img: "bbubbu",
      seasonIdx: 3,
      type: "villain",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "캔디핑",
      img: "candy",
      seasonIdx: 3,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "머랭핑",
      img: "meorang",
      seasonIdx: 3,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "샌드핑",
      img: "sand",
      seasonIdx: 3,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "또너핑",
      img: "ddoneo",
      seasonIdx: 3,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "와플핑",
      img: "waffle",
      seasonIdx: 3,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "롤리핑",
      img: "lolli",
      seasonIdx: 3,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "마카핑",
      img: "maca",
      seasonIdx: 3,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "핫케핑",
      img: "hotca",
      seasonIdx: 3,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "커핑",
      img: "keo",
      seasonIdx: 3,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "머핑",
      img: "meo",
      seasonIdx: 3,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "요거핑",
      img: "yogeo",
      seasonIdx: 3,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "눈꽃핑",
      img: "nunggot",
      seasonIdx: 3,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "푸딩핑",
      img: "pudding",
      seasonIdx: 3,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "멜로핑",
      img: "mello",
      seasonIdx: 3,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "쪼꼬핑",
      img: "zzoggo",
      seasonIdx: 3,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "뿌뿌핑",
      img: "bbubbu",
      seasonIdx: 3,
      type: "normal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
  ],
  fifth: [
    {
      name: "스타 하츄핑",
      img: "starhachu",
      seasonIdx: 4,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "빛나핑",
      img: "bitna",
      seasonIdx: 4,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "초롱핑",
      img: "chorong",
      seasonIdx: 4,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "빤짝핑",
      img: "bbanzzak",
      seasonIdx: 4,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill: `<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.`,
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
  ],
};
