export interface Ping {
  name: string;
  img: string;
  seasonIdx: number;
  type: string;
  line: string;
  gender: string;
  item: string;
  skill: string;
  like: string;
  hate: string;
  romi?: string;
  youtube?: string;
}

export interface Season {
  seasonIdx: number;
  name: string;
  color: string;
  filterKey: string;
}

export const colors: { [key: string]: string } = {
  first: "#FF69B4",
  second: "#90E7FE",
  third: "#E44C59",
  fourth: "#E1A5E6",
  fifth: "#666CD7",
  royal: "#fb923c",
  legend: "#7c3aed",
  normal: "#16a34a",
  villain: "#334155",
};

export const pingTypeData: { [key: string]: string } = {
  normal: "일반",
  royal: "로열",
  legend: "레전드",
  villain: "빌런",
};

export const seasonData: Season[] = [
  {
    seasonIdx: 1,
    name: "1기(큐브)",
    color: colors.first,
    filterKey: "first",
  },
  {
    seasonIdx: 2,
    name: "2기(보석)",
    color: colors.second,
    filterKey: "second",
  },
  {
    seasonIdx: 3,
    name: "3기(열쇠)",
    color: colors.third,
    filterKey: "third",
  },
  {
    seasonIdx: 4,
    name: "4기(디저트)",
    color: colors.fourth,
    filterKey: "fourth",
  },
  {
    seasonIdx: 5,
    name: "5기(스타)",
    color: colors.fifth,
    filterKey: "fifth",
  },
];

export const pingData: { [key: string]: Ping[] } = {
  first: [
    {
      name: "하츄핑",
      img: "hachu",
      seasonIdx: 0,
      type: "royal",
      line: "내 사랑을 듬뿍듬뿍 줄게~ 츄~♥",
      gender: "여성",
      item: "손거울",
      skill: "<사랑의 빛> 밝은 빛으로 적들을 방해할 수 있다.",
      like: "손거울을 보며 사랑스러운 표정 연습하기, 생크림 딸기 케이크, 딸기",
      hate: "억지로 잠을 깨우는 것, 갑자기 깜짝 놀라게 하는 것, 신맛이 나는 모든 것",
      romi: "프린세스 하트, 프린세스 베로니카",
      youtube: "https://www.youtube.com/embed/Acrv8EqCa4o",
    },
    {
      name: "바로핑",
      img: "baro",
      seasonIdx: 0,
      type: "royal",
      line: "바로핑에게 맡겨주세요, 바롬!",
      gender: "남성",
      item: "마법책",
      skill:
        "① <올바른 문법> 기호/이모티콘을 만들어 날릴 수 있다.\n② 상대가 '바른 생활'을 하도록 만들 수 있다.",
      like: "깔끔하게 정돈된 환경, 독서, 공부, 뭔가를 가르치기",
      hate: "늦잠, 게으름, 무질서한 상태, 더러운 환경",
      romi: "프린세스 클라우디아, 프린세스 베로니카",
      youtube: "https://www.youtube.com/embed/_V6o4WlY5jE",
    },
    {
      name: "아자핑",
      img: "aja",
      seasonIdx: 0,
      type: "royal",
      line: "내가 저 친구를 도와주지, 아잣!!",
      gender: "남성",
      item: "카메라",
      skill:
        "① <용기의 플래시> 상대를 잠시동안 움직이지 못하게 만든다.\n② 대상에게 잠시동안 '용기'를 북돋아줄 수 있다.",
      like: "체력단련, 격투기 및 액션 영화 보기",
      hate: "두려움, 도망치기, 포기하기",
      romi: "프린세스 스타, 프린세스 베로니카",
      youtube: "https://www.youtube.com/embed/wfGmhORpsmk",
    },
    {
      name: "차차핑",
      img: "chacha",
      seasonIdx: 0,
      type: "royal",
      line: "차차핑이 희망을 줄게, 차차~",
      gender: "여성",
      item: "물뿌리개",
      skill: `① <희망의 물줄기> 물을 뿌려 팅클퍼프 마법을 풀 수 있다.\n② 사물/대상의 크기를 키우거나, 시든 식물을 생생하게 만든다.`,
      like: "화초에 물 주기, 식물 보살피기, 꽃 향기 맡기, 격려하기",
      hate: "꽃을 꺾거나 잔디를 밟는 등의 행동, 부정적인 말과 행동",
      romi: "프린세스 클로버, 프린세스 베로니카",
      youtube: "https://www.youtube.com/embed/BMGBMX8qhZI",
    },
    {
      name: "라라핑",
      img: "rara",
      seasonIdx: 0,
      type: "royal",
      line: "이럴 땐 노래를 불러야겠어, 라랑!",
      gender: "여성",
      item: "마이크",
      skill:
        "① <즐거운 댄스> 대상이 춤을 추게 만들 수 있다.\n② 대상이 잠시동안 무언가를 '즐겁게' 느끼게 만들 수 있다.\n③ 마이크를 사용해, 자신이 아닌 다른 이의 목소리를 낼 수 있다.",
      like: "노래와 춤, 신나는 놀이, 수다",
      hate: "심각한 분위기, 지루한 것",
      romi: "프린세스 멜로디, 프린세스 베로니카",
      youtube: "https://www.youtube.com/embed/vndue5xne2o",
    },
    {
      name: "해핑",
      img: "hae",
      seasonIdx: 0,
      type: "royal",
      line: "꺄아~ 목욕탕에서 비눗방울로 놀 때가 제~일 행복해~ 해피!",
      gender: "여성",
      item: "비눗방울 장난감",
      skill:
        "① <행복의 방울방울> 비눗방울 안에 대상을 가두거나, 누군가를 태워 이동시킬 수 있다.\n② 대상을 잠시동안 행복하게 만들 수 있다.",
      like: "비눗방울 놀이, 낙서하기, 다른 티니핑 행동 따라하기",
      hate: "더 놀고 싶은데 자야 하는 것",
      romi: "프린세스 선샤인, 프린세스 베로니카",
      youtube: "https://www.youtube.com/embed/w_qrXVT4WU4",
    },
    {
      name: "악동핑",
      img: "akdong",
      seasonIdx: 0,
      type: "villain",
      line: "나는야~ 장난치기, 골탕 먹이기의 천재! 엉망진창 만들기를 좋아하는 티니핑이시다~, 통통~!",
      gender: "여성",
      item: "뿅망치",
      skill: "<번개 뿅망치>\n번개를 발사해, 상대를 공격할 수 있다.",
      like: "장난치기, 골탕 먹이기",
      hate: "간섭 받는 것, 명령 받는 것",
      youtube: "https://www.youtube.com/embed/L-FbH_FGcm0",
    },
    {
      name: "앙대핑",
      img: "angdae",
      seasonIdx: 0,
      type: "villain",
      line: "내가 가진 마법으로 이 세상을 엉망진창으로 만들어주지, 앙앙!",
      gender: "여성",
      item: "삼지창",
      skill:
        "① 꽃가루를 뿌려, 꽃가루에 맞은 대상들이 서로 다투게 만들 수 있다.\n② 꽃가루의 독으로 상대를 깊은 잠에 빠지게 할 수 있다.",
      like: "엉망진창, 자유, 강한 것",
      hate: "질서, 봉인되는 것, 약한 것",
      youtube: "https://www.youtube.com/embed/llWog7Ld5Lk",
    },
    {
      name: "키키핑",
      img: "kiki",
      seasonIdx: 0,
      type: "normal",
      line: "키히히, 약오르지롱~ 키키!",
      gender: "남성",
      item: "막대사탕",
      skill:
        "<약오르지롱>\n막대사탕으로 팅클퍼프를 뿌려 상대방을 장난꾸러기로 만든다.",
      like: "재미있는 것, 장난",
      hate: "심심한 것, 지루한 것",
      youtube: "https://www.youtube.com/embed/DRARoenoxUg",
    },
    {
      name: "아잉핑",
      img: "aing",
      seasonIdx: 0,
      type: "normal",
      line: "애교로 넘어가줘잉~ 아잉~아잉~!",
      gender: "여성",
      item: "리본봉",
      skill:
        "<사랑해줘 아잉>\n리본봉으로 팅클퍼프를 뿌려 상대방을 심각한 애교쟁이로 만든다.",
      like: "솜사탕",
      hate: "심각한 상황",
      youtube: "https://www.youtube.com/embed/dXeEDedSwGM",
    },
    {
      name: "부끄핑",
      img: "bouque",
      seasonIdx: 0,
      type: "normal",
      line: "자꾸 쳐다보니까 부끄럽잖앙, 부끄부끄~!",
      gender: "여성",
      item: "당근쿠션",
      skill:
        "<붉은 당근쿠션>\n당근쿠션으로 팅클퍼프를 뿌려 상대방을 엄청난 부끄럼쟁이로 만든다.",
      like: "숨바꼭질",
      hate: "주목 받는 것",
      youtube: "https://www.youtube.com/embed/hsIgR6gyfeQ",
    },
    {
      name: "부투핑",
      img: "butu",
      seasonIdx: 0,
      type: "normal",
      line: "한번 겨뤄보라고, 투!",
      gender: "남성",
      item: "눈사람",
      skill:
        "<경기 시작>\n① 잠시동안 상대가 승부욕에 불타오르게 만들 수 있다.\n② 자신의 마음을 차갑게 감출 수 있어, 콤팩트에 감지되기 힘들다.",
      like: "대결, 경쟁, 승부",
      hate: "느릿느릿하고 느긋한 것",
      youtube: "https://www.youtube.com/embed/cgFVSnvhIyY",
    },
    {
      name: "깜빡핑",
      img: "ggambbak",
      seasonIdx: 0,
      type: "normal",
      line: "아...? 내가 여기 왜 왔더라, 깜빡?",
      gender: "남성",
      item: "지우개",
      skill:
        "<잊어버려 지우개>\n① 대상이 잠시동안 '깜빡' 잊어버리게 만들 수 있다.\n② 지우개로 사물을 지우면, 사물이 순간적으로 사라졌다 나타난다.",
      like: "여유, 느긋함",
      hate: "정확한 규율과 규칙, 바로핑의 잔소리!",
      youtube: "https://www.youtube.com/embed/-4P0sHvYcvI",
    },
    {
      name: "띠용핑",
      img: "ddiyong",
      seasonIdx: 0,
      type: "normal",
      line: "뭐 또 재미있는 일 없나? 띠용!",
      gender: "여성",
      item: "마술사 모자와 마술봉",
      skill:
        "<나타났다 띠용>\n① 대상에게 잠시동안 '허상'이 보이게 할 수 있다.\n② 자신의 모습을 바꿀 수 있지만, 완벽하지 않다.",
      like: "재미있고 엉뚱한 상상하기",
      hate: "상상력을 제한하는 모든 것!",
      youtube: "https://www.youtube.com/embed/K54kWfZMLps",
    },
    {
      name: "주르핑",
      img: "jur",
      seasonIdx: 0,
      type: "normal",
      line: "비를 보고 있으면... 나도 모르게 눈물이 나, 주르...",
      gender: "여성",
      item: "나뭇잎 우산",
      skill:
        "<한줄기의 눈물>\n① 대상에게 비를 내려 울게 만들고, 그 눈물을 사탕으로 만든다.\n② 나뭇잎 우산을 이용해 일정거리를 날아갈 수 있다.",
      like: "다양한 맛의 눈물사탕! 그리고 비!",
      hate: "소란스러운 것",
      youtube: "https://www.youtube.com/embed/MbhnysPgLHw",
    },
    {
      name: "차나핑",
      img: "chana",
      seasonIdx: 0,
      type: "normal",
      line: "아... 점점 귀찮아지네... 그냥 잡혀...? 말아...? 차나~!",
      gender: "남성",
      item: "커다란 베개",
      skill:
        "<너무 귀찮아>\n① 상대의 의욕을 상실시키며, 행동이 느려지게 한다.\n② 자신의 몸을 투명하게 만들 수 있다.",
      like: "낮잠, 주말, 그리고 모순적이지만 빠른 자동차!",
      hate: "별 것 아닌데 말 시키는 것, 바로핑의 잔소리",
      youtube: "https://www.youtube.com/embed/939SlTM6A50",
    },
    {
      name: "따라핑",
      img: "ddara",
      seasonIdx: 0,
      type: "normal",
      line: "모두 헤이쥬의 춤을 따라해볼까?! 따랏, 따랏~!",
      gender: "남성",
      item: "쌍안경",
      skill:
        "<날 따라따라>\n대상이 자신 또는 자신이 원하는 다른 누군가의 행동을\n일정 시간동안 따라하게 만들 수 있다.",
      like: "상대를 따라하며 약올리기, 가수 헤이쥬",
      hate: "약 올렸는데 반응이 없을 때! (자주 깜빡하는 깜빡핑에게는 장난치지 않는다)",
      youtube: "https://www.youtube.com/embed/sBI7LXuEaKY",
    },
    {
      name: "나르핑",
      img: "nar",
      seasonIdx: 0,
      type: "normal",
      line: "안녕? 난 나르핑~ 너 자신을 좀 더 사랑하게 만들어줄게, 나르~",
      gender: "여성",
      item: "립스틱",
      skill:
        "<난 너무 아름다워>\n① 마법손거울을 대상에게 줘서, 손거울 속 자신에게 빠지게 만든다.\n② 마법손거울 속 공간을 통해 공간이동을 할 수 있다.",
      like: "뷰티(외모관리), 아름다운 것",
      hate: "자신이 보기에 아름답지 않은 것",
      youtube: "https://www.youtube.com/embed/TfLAccPuqYs",
    },
    {
      name: "무셔핑",
      img: "musheo",
      seasonIdx: 0,
      type: "normal",
      line: "진짜 웃긴다, 무셔~! 저런 겁쟁이들! 이 무셔핑님처럼 용감해야지~!",
      gender: "남성",
      item: "손전등",
      skill:
        "<두려움의 플래시>\n대상이 무서워하는 것을 보여줘, 두려움에 떨게 만들 수 있다.",
      like: "할로윈 호박, 남들의 놀란 얼굴을 찍은 사진",
      hate: "겁쟁이라는 것을 들키는 것, 무시무시한 거미!",
      youtube: "https://www.youtube.com/embed/0Mr5DPA2qSk",
    },
    {
      name: "투투핑",
      img: "tutu",
      seasonIdx: 0,
      type: "normal",
      line: "내가 하츄핑보다 더 귀여운데! 왜 하츄핑만 특별히 예뻐하지?! 투잉!",
      gender: "여성",
      item: "아이섀도 팔레트와 섀도브러쉬",
      skill:
        "<날카로운 눈빛>\n대상에게 팅클퍼프를 뿌려, 대상의 질투심을 부추긴다.",
      like: "화장하기, 꾸미기, 그리고 로미공주님♥!",
      hate: "로미공주님이 자기보다 예뻐하는 것",
      youtube: "https://www.youtube.com/embed/11oauwomEAU",
    },
    {
      name: "차캐핑",
      img: "chakae",
      seasonIdx: 0,
      type: "normal",
      line: "참 잘했어요~ 정말 착한 아이네, 차캐!",
      gender: "여성",
      item: "차캐핑의 얼굴도장",
      skill:
        "① 대상에게 팅클퍼프를 뿌려, 대상이 다른 사람을 배려하게 만든다.\n② 착한 일을 한 아이에게 도장을 찍어주어, 그날 하루 왠지 좋은 일이 일어나게 만들 수 있다.",
      like: "다른 사람 도와주기, (도장을 찍어줄) 착한 아이",
      hate: "도움을 필요로 하는 사람을 외면하는 것, 나쁜 아이",
      youtube: "https://www.youtube.com/embed/ef7fjqXLwRY",
    },
    {
      name: "떠벌핑",
      img: "ddeobeol",
      seasonIdx: 0,
      type: "normal",
      line: "모두의 비밀을 떠벌리자~ 비밀을 말해, 떠벌~!",
      gender: "남성",
      item: "확성기",
      skill:
        "대상이 하려던 말이 아닌, 남의 비밀 등과 같이 속으로만 생각하던 다른 말을 하게 만들 수 있다.",
      like: "수다",
      hate: "침묵, 도서관",
      youtube: "https://www.youtube.com/embed/iQlZtO7gdE8",
    },
    {
      name: "다조핑",
      img: "dajo",
      seasonIdx: 0,
      type: "normal",
      line: "다 내 꺼야, 다조! 모두 다 가져올 거야, 다조!",
      gender: "여성",
      item: "바구니",
      skill:
        "① 대상에게 팅클퍼프를 뿌려, 잠시동안 욕심내게 만들 수 있다.\n② 바구니를 통해 원하는 것을 가져오거나, 필요한 것을 꺼낼 수 있다.",
      like: "맛있는 것과 반짝이는 것",
      hate: "칙칙하거나 우울한 것, 검정색이나 회색",
      youtube: "https://www.youtube.com/embed/w7pIQ6ho6QI",
    },
    {
      name: "화나핑",
      img: "hwana",
      seasonIdx: 0,
      type: "normal",
      line: "화 날 만한 이유가 있었다궁~! 화낭!",
      gender: "남성",
      item: "부채",
      skill:
        "① 대상에게 팅클퍼프를 뿌려, 잠시동안 화가 나게 만들 수 있다.\n② 화가 나면, 열기를 발산해 주변 식물을 시들어 버리게 한다.",
      like: "화나는 것",
      hate: "화나는 게 화낭!",
      youtube: "https://www.youtube.com/embed/C_bTQZ3iec4",
    },
    {
      name: "시러핑",
      img: "shireo",
      seasonIdx: 0,
      type: "normal",
      line: "나는야~ 모든 게 싫다네~ 시러시러~",
      gender: "남성",
      item: "X자 팻말",
      skill:
        "① 대상이 한순간 거절하는 마음이 들게 할 수 있다.\n② 팻말이 방패 역할을 해, 물리적인 접근을 막을 수 있다.",
      like: "상대의 말에 반대하기, 브로콜리",
      hate: "다수결",
      youtube: "https://www.youtube.com/embed/NlXIMumhxD4",
    },
    {
      name: "바네핑",
      img: "bane",
      seasonIdx: 0,
      type: "normal",
      line: "서로 사랑해야지, 바네~!",
      gender: "여성",
      item: "활과 화살",
      skill: "화살에 맞은 대상이 처음 발견하는 것에 반하게 만들 수 있다.",
      like: "하트 모양, 빨간색",
      hate: "불평하고 서로 싸우는 것, 사랑이 깨지는 것",
      youtube: "https://www.youtube.com/embed/zAGGhBiW_ow",
    },
    {
      name: "덜덜핑",
      img: "deoldeol",
      seasonIdx: 0,
      type: "normal",
      line: "감히 내 집을 빼앗아가다니! 너희도 덜덜 떨어보라고, 덜덜!",
      gender: "남성",
      item: "막대 아이스크림",
      skill: "① 사물을 얼릴 수 있다.\n② 대상이 추위를 느끼게 할 수 있다.",
      like: "차가운 것, 단짝친구 꽁꽁핑",
      hate: "뜨거운 것, 더운 것",
      youtube: "https://www.youtube.com/embed/fwowOYDe1rs",
    },
    {
      name: "그림핑",
      img: "grim",
      seasonIdx: 0,
      type: "normal",
      line: "난 그림만 그릴 수 있으면 행복해, 그림~",
      gender: "남성",
      item: "물감 붓",
      skill: "자신이 그린 그림을 실체화 시킬 수 있다.",
      like: "아름다운 것 (예술)",
      hate: "아름답지 않은 것",
      youtube: "https://www.youtube.com/embed/C_ZSf1FxoFM",
    },
    {
      name: "무거핑",
      img: "mugeo",
      seasonIdx: 0,
      type: "normal",
      line: "이런 무거운 걸 들 수 있는 나란 녀석은 역시 멋져~!",
      gender: "남성",
      item: "아령",
      skill: "사물을 무겁게 만들 수 있다.",
      like: "멋진 포즈를 취하기",
      hate: "가볍게 촐싹대는 것",
      youtube: "https://www.youtube.com/embed/QD9nl3SNhWM",
    },
    {
      name: "꺼꿀핑",
      img: "ggeoggul",
      seasonIdx: 0,
      type: "normal",
      line: "역시 세상은 거꾸로 봐야 제 맛이지, 꺼꿀!",
      gender: "남성",
      item: "자석(말굽자석)",
      skill:
        "① 대상을 반대로 움직이게 할 수 있다.\n② 대상을 거꾸로 서게 만들 수 있다.",
      like: "피망, 당근 등의 채소",
      hate: "달콤한 것",
      youtube: "https://www.youtube.com/embed/9fAQyGni7-I",
    },
    {
      name: "씽씽핑",
      img: "ssingssing",
      seasonIdx: 0,
      type: "normal",
      line: "그 정도 속도로는 어림없지, 씽씽!",
      gender: "남성",
      item: "킥보드",
      skill: "대상의 스피드를 자유자재로 제어할 수 있다.",
      like: "제트기 등의 빠른 것",
      hate: "거북이, 달팽이 등 느린 것",
      youtube: "https://www.youtube.com/embed/Pi8qp9x6BEo",
    },
    {
      name: "베베핑",
      img: "bebe",
      seasonIdx: 0,
      type: "normal",
      line: "아기가 되어 봐! 베베~! 헤헤헷! 아기가 되니까 좋지? 베베!",
      gender: "여성",
      item: "딸랑이, 보행기",
      skill: "대상을 아기로 만들 수 있다.",
      like: "아기, 자장가",
      hate: "어른, 자는 데 깨우는 것",
      youtube: "https://www.youtube.com/embed/7vnIv4E3M94",
    },
    {
      name: "코자핑",
      img: "koja",
      seasonIdx: 0,
      type: "normal",
      line: "지금이라면 엄청 달콤한 꿈을 꿀 거야! 잠에 빠져라~ 코자~!",
      gender: "남성",
      item: "청소기",
      skill:
        "대상을 잠들게 할 수 있다.\n대상이 잠들면, 꿈을 들여다보고 꿈젤리를 만든다.",
      like: "반짝이는 꿈젤리",
      hate: "악몽젤리",
      youtube: "https://www.youtube.com/embed/iWg6EYqHo_Y",
    },
    {
      name: "딱풀핑",
      img: "ddakpul",
      seasonIdx: 0,
      type: "normal",
      line: "왜 이렇게 싸우는 거야? 안 되겠군. 사이좋게 붙어라, 딱딱~!",
      gender: "여성",
      item: "딱풀",
      skill:
        "① 싸우는 대상 둘을 붙여버릴 수 있다.\n② 상대를 어디엔가 붙여버릴 수 있다.",
      like: "사이좋게 지내는 것",
      hate: "서로 싸우는 것",
      youtube: "https://www.youtube.com/embed/W9EcrGrVPIY",
    },
    {
      name: "모야핑",
      img: "moya",
      seasonIdx: 0,
      type: "normal",
      line: "모야모야, 궁금해! 커져라~! 모야!",
      gender: "여성",
      item: "돋보기",
      skill: "물건 혹은 대상의 크기를 거대하게 키울 수 있다.",
      like: "호기심을 자극하는 모든 것",
      hate: '궁금증이 풀리지 않는 답답한 상황\n"모야모야모야! 도대체 모야!"',
      youtube: "https://www.youtube.com/embed/mmK4WijfQ1w",
    },
    {
      name: "토이핑",
      img: "toy",
      seasonIdx: 0,
      type: "normal",
      line: "장난감이 되어라~ 토이토이! 이번엔 이걸로 놀아야지~ 토이!",
      gender: "여성",
      item: "요요",
      skill: "물건 혹은 대상을 장난감으로 만들 수 있다.",
      like: "장난감, 재밌는 것",
      hate: "독서, 지루한 것",
      youtube: "https://www.youtube.com/embed/CyYSkZfVx00",
    },
    {
      name: "또까핑",
      img: "ddogga",
      seasonIdx: 0,
      type: "normal",
      line: "난 또까핑~! 다른 사람의 모습을 똑같이 복사하는 변신의 천재야~!",
      gender: "여성",
      item: "가면",
      skill: "가면을 이용해, 물건 혹은 대상의 모습을 복사할 수 있다.",
      like: "쌍둥이, 성대모사, 남 따라하기",
      hate: "누가 자신을 따라하는 것 (따라핑!)",
      youtube: "https://www.youtube.com/embed/BPVCPwuuNPQ",
    },
    {
      name: "플라핑",
      img: "fla",
      seasonIdx: 0,
      type: "normal",
      line: "너희도 꽃이 되어 꺾인 꽃의 아픔을 느껴보라고! 꽃이 되어라, 플랑~",
      gender: "남성",
      item: "장미꽃 한 송이",
      skill: "대상 혹은 사물을 꽃으로 만들 수 있다.",
      like: "장미, 해바라기, 튤립 등",
      hate: "곤충, 벌레",
      youtube: "https://www.youtube.com/embed/Azo8B50vIrc",
    },
    {
      name: "노라핑&노리핑",
      img: "noranori",
      seasonIdx: 0,
      type: "normal",
      line: "드디어 자유다, 노라~! 저리 가, 형아 게임 중이잖아! / 노~리! 형아~ 형아~! 노리~ 노리",
      gender: "남성 / 남성",
      item: "게임기 / 젖병",
      skill:
        "팅클퍼프로 대상이 하던 것을 중단하고 놀기만 하게 만들 수 있다.\n염력... 이지만 '아기'이니만큼 잠재력이 많아 단언할 수 없다!",
      like: "놀이터, 장난감, 게임기 / 노라핑, 우유, 단 두 개 뿐인 소중한 이빨!",
      hate: "공부, 일찍 자기 / 상한 우유",
      youtube: "https://www.youtube.com/embed/pR8kXGsMSzs",
    },
    {
      name: "아휴핑",
      img: "ahew",
      seasonIdx: 0,
      type: "normal",
      line: "아휴... 좋은 소리가 안 나오네, 아휴...",
      gender: "여성",
      item: "나팔",
      skill: "나팔소리를 들으면 우울해져 한숨이 나오게 한다.",
      like: "포기, 우울한 생각하기",
      hate: "즐거운 생각하기",
      youtube: "https://www.youtube.com/embed/cw1mpi0zCGQ",
    },
    {
      name: "똑똑핑",
      img: "ddokddok",
      seasonIdx: 0,
      type: "normal",
      line: "시끄러워~! 공부하는데 방해하지 마~ 똑똑!",
      gender: "남성",
      item: "큰 연필과 책",
      skill:
        "① 언제 어디서든 책상과 의자를 소환해 공부한다.\n② 대상을 일시정지시키고, 구구단을 외우게 만든다.\n단, 대상이 웃으면 마법이 풀린다.",
      like: "공부, 조용한 곳, 바로핑",
      hate: "놀기, 시끄러운 곳",
      youtube: "https://www.youtube.com/embed/iyStA4IBtEg",
    },
    {
      name: "꽁꽁핑",
      img: "ggonggong",
      seasonIdx: 0,
      type: "normal",
      line: "흥~ 거기서 꽁꽁 얼어 있으라구, 꽁꽁!”",
      gender: "남성",
      item: "아이스크림 콘",
      skill:
        "① 대상이나 사물을 얼릴 수 있다.\n② 대상에게 (덜덜핑 모양의) 아이스크림을 씌울 수 있다.\n③ 단짝친구 아이스 마법: 덜덜핑과의 우정을 뜻하는 마법으로,\n서로의 얼굴 모양 아이스크림을 만들 수 있다.",
      like: "겨울, 눈사람, 빙수, 그리고 덜덜핑!",
      hate: "여름, 더운 곳, 난로",
      youtube: "https://www.youtube.com/embed/v0rw-cKh5Hg",
    },
    {
      name: "찌릿핑",
      img: "zzirit",
      seasonIdx: 0,
      type: "normal",
      line: "짜릿짜릿하니까 좋잖아? 또 짜릿한 일 있나 찾으러 가야지! 찌릿!",
      gender: "남성",
      item: "번개 지팡이",
      skill:
        "① 전기를 발생시켜 상대를 감전시킬 수 있다.\n② 전기가 있는 곳이라면 어디든 공간이동할 수 있다.\n(예: 콘센트를 통해 방을 오갈 수 있다.)",
      like: "전기, 전구, 천둥, 번개",
      hate: "정전, 고장난 전구, 무료함",
      youtube: "https://www.youtube.com/embed/Ada1fejSh-o",
    },
    {
      name: "홀로핑",
      img: "holo",
      seasonIdx: 0,
      type: "normal",
      line: "나는 혼자서 지내는 게 좋아, 홀로!",
      gender: "남성",
      item: "낚싯대",
      skill: "낚싯대를 휘둘러 방어막을 만들 수 있다.",
      like: "아무도 없는 곳",
      hate: "떠들썩한 분위기",
      youtube: "https://www.youtube.com/embed/m1LXmYbwULo",
    },
  ],
  second: [
    {
      name: "다이아 하츄핑",
      img: "diahachu",
      seasonIdx: 1,
      type: "royal",
      line: "내 사랑을 듬뿍듬뿍 줄게~ 츄~♥",
      gender: "여성",
      item: "하프",
      skill:
        "<사랑의 선율> 하트 모양 음표를 발사하거나, 대상의 진로를 방해하거나, 행동에 제약을 줄 수 있다.",
      like: "차 마시기, 하프 치기, 생크림 딸기 케이크, 딸기",
      hate: "억지로 잠을 깨우는 것, 갑자기 깜짝 놀라게 하는 것, 신맛이 나는 모든 것",
      romi: "프린세스 다이아하트",
      youtube: "https://www.youtube.com/embed/DMNhTS5RECA",
    },
    {
      name: "조아핑",
      img: "joa",
      seasonIdx: 1,
      type: "royal",
      line: "많이 속상했겠다... 괜찮아, 내가 도와줄게, 조아~",
      gender: "여성",
      item: "브러쉬",
      skill:
        "<친절의 쓰담쓰담>\n동물들과 대화할 수 있고, 동물들을 컨트롤할 수 있다.",
      like: "동물들 빗질하기, 먹이 주기 등 동물을 보살피는 것, 마카롱",
      hate: "이기적인 말과 행동, 동물을 괴롭히는 등의 행동, 매운 것",
      romi: "프린세스 에메랄드",
      youtube: "https://www.youtube.com/embed/osGnQPDtWTQ",
    },
    {
      name: "방글핑",
      img: "bangle",
      seasonIdx: 1,
      type: "royal",
      line: "친구를 구하고 싶은 마음은 누구보다도 커, 방글!",
      gender: "여성",
      item: "폭죽",
      skill:
        "<웃음의 깜짝쇼>\n폭죽을 펑! 터트려 랜덤 아이템이 등장하게 할 수 있다.",
      like: "웃음소리, 재미있는 놀이, 뭐든지 첫번째로 하기!, 민트 초코 케이크",
      hate: "잔소리, 인내하는 것, 엄숙한 분위기, 쿠키! (가루를 흘리면 하츄핑이 잔소리를 한다구, 방글!)",
      romi: "프린세스 루비",
      youtube: "https://www.youtube.com/embed/0YKUhTBzFRA",
    },
    {
      name: "믿어핑",
      img: "miteo",
      seasonIdx: 1,
      type: "royal",
      line: "와아~! 네 말이 맞아, 미더!",
      gender: "남성",
      item: "우산",
      skill:
        "<믿음의 수호>\n상대의 공격을 방어하거나, 우산을 펼쳐서 상대에게 마법을 발사할 수 있다.",
      like: "목욕하기, 비오는 날, 해가 쨍쨍한 날, 초코볼",
      hate: "거짓말, 독서, 바람 부는 날 (“우산이 뒤집히잖아, 미더!”), 건포도",
      romi: "프린세스 사파이어",
      youtube: "https://www.youtube.com/embed/KOzYFKhES8A",
    },
    {
      name: "가면핑",
      img: "gamyeon",
      seasonIdx: 1,
      type: "villain",
      line: "",
      gender: "?",
      item: "열쇠, 최면 피리",
      skill: "원하는 마법을 부릴 수 있다.",
      like: "?",
      hate: "?",
      youtube: "https://www.youtube.com/embed/lTuYDv2pH7Q",
    },
    {
      name: "다해핑",
      img: "dahae",
      seasonIdx: 1,
      type: "villain",
      line: "흥! 제니에게 무례하게 굴어선 안 되지, 다해!",
      gender: "여성",
      item: "비녀",
      skill:
        "<헌신의 만능열쇠>(2기) → <전류의 비녀>(3기)\n전류 마법을 기본으로 사용하지만,\n왕립 티니핑 스쿨 수석 졸업생인만큼 다양한 마법을 사용할 수 있다.",
      like: "제니, 제니와 함께하는 시간 전부",
      hate: "제니에게 무례한 사람이나 행동",
      youtube: "https://www.youtube.com/embed/nCrwl_QVmHY",
    },
    {
      name: "까르핑",
      img: "ggar",
      seasonIdx: 1,
      type: "normal",
      line: "너희도 간지럼 태워줄게~ 까르~",
      gender: "여성",
      item: "깃털부채",
      skill:
        "<간지럼 부채>\n대상이 요상한 상태로 간지럼을 타며\n자지러지게 웃게 만들 수 있다.",
      like: "간지럼 태우기",
      hate: "누군가가 간지럼을 참는 것",
      youtube: "https://www.youtube.com/embed/8J1UuS3adlk",
    },
    {
      name: "아야핑",
      img: "aya",
      seasonIdx: 1,
      type: "normal",
      line: "후잉... 도대체 여긴 어디야...? 집에 가고 싶어, 아야!",
      gender: "여성",
      item: "반창고",
      skill: "<엄살 반창고>\n대상이 과도한 엄살을 피우게 만들 수 있다.",
      like: "안 아픈 것, 우리 집(보석숲!)",
      hate: "아픈 것, 병원, 보석숲을 떠나는 것",
      youtube: "https://www.youtube.com/embed/Oiq4Bs5Jk7o",
    },
    {
      name: "소원핑",
      img: "sowon",
      seasonIdx: 1,
      type: "normal",
      line: "난 소원핑이야. 세가지 소원을 이뤄 줄게, 소원~!",
      gender: "여성",
      item: "요술램프",
      skill:
        "<엉뚱한 소원>\n대상의 세가지 소원을 이뤄줄 수 있다.\n단, 대상이 원하는 방식은 아닐 수도...?",
      like: "우유, 친구들, 소원 들어주기",
      hate: "거짓말, 남을 다치게 하는 것",
      youtube: "https://www.youtube.com/embed/1GB4Xg1-IuM",
    },
    {
      name: "토닥핑",
      img: "todak",
      seasonIdx: 1,
      type: "normal",
      line: "언제나 친구들을 위로해 줄 거야, 토닥토닥!",
      gender: "여성",
      item: "애착담요",
      skill: "<담요의 위안>\n실의에 빠진 대상에게 위안을 줄 수 있다.",
      like: "위로하기, 격려하기, 포기하지 않기",
      hate: "좌절, 절망, 포기",
      youtube: "https://www.youtube.com/embed/C2Og4mqjjdU",
    },
    {
      name: "쪼꼼핑",
      img: "zzoggom",
      seasonIdx: 1,
      type: "normal",
      line: "꼭꼭 숨을래, 쪼꼼! 아무도 못 찾게 얼른 숨어야 하는데, 쪼꼼...",
      gender: "남성",
      item: "아코디언",
      skill: "<마법의 사물 축소>\n대상이나 사물의 크기를 작게 만들 수 있다.",
      like: "조아핑, 숨바꼭질, 친구들",
      hate: "대범한 행동, 민폐 끼치기",
      youtube: "https://www.youtube.com/embed/5Mq-hDm3slQ",
    },
    {
      name: "싹싹핑",
      img: "ssakssak",
      seasonIdx: 1,
      type: "normal",
      line: "아휴... 지저분한 건 정리정돈부터, 싹싹! 깨끗하게 싹싹!",
      gender: "여성",
      item: "빗자루",
      skill:
        "<빗자루의 정리정돈>\n사물이 저절로 정리정돈되게 하거나,\n대상이 주변을 열심히 청소/정리정돈하게 만들 수 있다.",
      like: "깨끗한 것, 청소, 정리정돈",
      hate: "더러운 것, 지저분한 것, 어질러진 것",
      youtube: "https://www.youtube.com/embed/eIhm5OYopm0",
    },
    {
      name: "맛나핑",
      img: "matna",
      seasonIdx: 1,
      type: "normal",
      line: "요래요래 맛낭~! 맛나낭~ 맛낭~ 지는 맛나핑이라고 해유, 맛낭~!",
      gender: "여성",
      item: "국자",
      skill:
        "<요리의 국자>\n마법을 사용해 요리를 하거나,\n대상이 맛나핑과 함께 요리하게 만들 수 있다.",
      like: "요리하기, 맛있는 음식",
      hate: "맛없는 음식",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/aJVK-tjDiOw",
    },
    {
      name: "포근핑",
      img: "pogeun",
      seasonIdx: 1,
      type: "normal",
      line: "내가 포근하게 해줄게, 포근~! 모두모두 포근해져라, 포근~!",
      gender: "여성",
      item: "뜨개바늘",
      skill:
        "<변신 뜨개질>\n생명체를 제외한 대상을 양털 뜨개로 된 소품으로 바꿀 수 있다.",
      like: "뜨개질, 포근한 것",
      hate: "딱딱한 것, 차가운 것, 날카로운 것",
      youtube: "https://www.youtube.com/embed/IzqRzezxJeE",
    },
    {
      name: "메모핑",
      img: "memo",
      seasonIdx: 1,
      type: "normal",
      line: "쓰기만 하면 뭐든 이뤄진다니까~ 메모~!",
      gender: "여성",
      item: "다이어리와 펜",
      skill:
        "<뭐든 이루어지는 메모>\n대상을 보면서 다이어리에 메모를 적으면,\n메모에 적은 대로 사건이 실제로 이루어지게 할 수 있다.",
      like: "메모하기, 관심, 친구들",
      hate: "무관심",
      youtube: "https://www.youtube.com/embed/obMDHsIh34c",
    },
    {
      name: "공쥬핑",
      img: "gongzu",
      seasonIdx: 1,
      type: "normal",
      line: "공주라면 당연히 해야 할 일인걸~! 소중한 나의 왕국은 내가 지켜낼 거야, 공쥬!",
      gender: "여성",
      item: "마법봉(로드스틱)",
      skill:
        "<역할 변신>\n대상을 자신이 바라는 직위로 만들어,\n자신이 원하는 대로 행동하게 만들 수 있다.",
      like: "공주, 우아한 것, 나의 왕국, 나의 백성들",
      hate: "촌스러운 것, 못된 마법사",
      youtube: "https://www.youtube.com/embed/Rko8klJO9Vc",
    },
    {
      name: "짝짝핑",
      img: "zzakzzak",
      seasonIdx: 1,
      type: "normal",
      line: "짝꿍이 됩시다, 짝짝! 둘둘둘~ 짝이 좋아~ 짝짝!",
      gender: "남성",
      item: "캐스터네츠",
      skill:
        "<마법의 짝짝 복제>\n대상을 복제하여 2개로 만들 수 있다.\n(단, 복제된 대상은 오리지널과 약간의 차이가 있다.\n그리고 본인 스스로는 복제할 수 없다.)",
      like: "둘씩 짝지어진 모든 것, 짝수",
      hate: "하나인 것, 짝 잃은 양말, 홀수",
      youtube: "https://www.youtube.com/embed/-amBXlIEhoo",
    },
    {
      name: "주네핑",
      img: "june",
      seasonIdx: 1,
      type: "normal",
      line: "생일 축하행~ 주네~! 역시 선물 주는 건 즐거웡, 주네~!",
      gender: "여성",
      item: "선물 상자",
      skill:
        "<깜짝 선물 상자>\n대상에게 줄 선물을 마법으로 만들어 줄 수 있다.\n이 선물은 대상자가 가장 원하는 것이며,\n주네핑도 그 내용물을 알지 못한다.",
      like: "선물 주기, 착한 일",
      hate: "선물을 못 주는 것",
      youtube: "https://www.youtube.com/embed/JDwkPbQgae0",
    },
    {
      name: "뚝딱핑",
      img: "ddukddak",
      seasonIdx: 1,
      type: "normal",
      line: "이제 걸작을 완성해야 하니까... 방해하지 말아 줄래, 뚝딱!",
      gender: "남성",
      item: "망치",
      skill: "<마법의 조각상>\n본인이 만든 조각을 움직이게 만들 수 있다.",
      like: "멋진 조각들, 걸작, 반짝반짝(영감)!",
      hate: "볼품 없는 것",
      youtube: "https://www.youtube.com/embed/10SLXtnx0zs",
    },
    {
      name: "발레핑",
      img: "ballet",
      seasonIdx: 1,
      type: "normal",
      line: "자, 날 봐~ 이렇게~ 발레에는 우아함이 필요해~. 핑그르르, 발레~!",
      gender: "여성",
      item: "스노우볼",
      skill: "<마법의 발레>\n대상이 발레 동작을 하게 만들 수 있다.",
      like: "발레",
      hate: "딱딱한 것",
      youtube: "https://www.youtube.com/embed/5_Z2aPI0cZU",
    },
    {
      name: "원더핑",
      img: "wonder",
      seasonIdx: 1,
      type: "normal",
      line: "그대, 도움이 필요한 것 같군. 내가 도와주지! 원더!!",
      gender: "여성",
      item: "부메랑",
      skill:
        "<마법의 부메랑 공격>\n대상에게 직접 혹은 간접적으로 타격을 줄 수 있다.\n그 외에도 악당을 물리치고\n사람들을 돕기 위해서라면 다양한 마법을 쓸 수 있다.",
      like: "히어로, 정의",
      hate: "악당, 불의",
      youtube: "https://www.youtube.com/embed/YTSvmpO5guM",
    },
  ],
  third: [
    {
      name: "플로라 하츄핑",
      img: "florahachu",
      seasonIdx: 2,
      type: "royal",
      line: "내 사랑을 듬뿍듬뿍 줄게~ 츄~♥",
      gender: "여성",
      item: "향수",
      skill:
        "<사랑의 향기> 향수를 뿌려서 상대 공격을 막을 수 있으며, 대상을 향기에 취하게 만들 수 있다.",
      like: "로미와 함께 있는 모든 순간, 생크림 딸기 케이크, 딸기",
      hate: "억지로 잠을 깨우는 것, 갑자기 깜짝 놀라게 하는 것, 신맛이 나는 모든 것",
      romi: "프린세스 플로라하트",
      youtube: "https://www.youtube.com/embed/Q7B496uQnzY",
    },
    {
      name: "꾸래핑",
      img: "ggurae",
      seasonIdx: 2,
      type: "royal",
      line: "친구들을 되돌릴 수 있는 건, 나뿐이니까, 꾸래!",
      gender: "여성",
      item: "눈사람",
      skill:
        "<평화의 눈덩이>\n눈사람으로 다양한 크기의 눈덩이를 만들 수 있다.\n<평화의 크리스탈>\n단단한 크리스탈 재질의 얼음으로 얼려 버린다.",
      like: "낮잠자기, 간식타임, 추운 날, 눈 오는 날",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 크리스탈",
      youtube: "https://www.youtube.com/embed/UPFCvEgd-P8",
    },
    {
      name: "나나핑",
      img: "nana",
      seasonIdx: 2,
      type: "royal",
      line: "내 덕분에 바로 프린세스 로미를 찾은 거라구, 나나!",
      gender: "여성",
      item: "해 모양 손거울",
      skill: "<열정의 반사>\n대상의 마법을 완벽하게 반사시킬 수 있다.",
      like: "따뜻한 곳, 햇빛 쨍한 날, 나!",
      hate: "대충하는 것, 의기소침한 분위기",
      romi: "프린세스 솔라리스",
      youtube: "https://www.youtube.com/embed/TQtziDTeEyo",
    },
    {
      name: "솔찌핑",
      img: "solzzi",
      seasonIdx: 2,
      type: "royal",
      line: "나 솔찌핑이야! 솔직함의 티니핑~!",
      gender: "남성",
      item: "구름 솜사탕",
      skill:
        "<솔직함의 뭉게뭉게>\n구름 솜사탕에서 마법 구름을 만들어낼 수 있다.",
      like: "놀고 먹고 자기, 비 오는 날, 구름이 많은 하늘",
      hate: "거짓말, 답답하고 불편한 것",
      romi: "프린세스 글로리아",
      youtube: "https://www.youtube.com/embed/x6ao0BkS9UI",
    },
    {
      name: "행운핑",
      img: "haengwoon",
      seasonIdx: 2,
      type: "legend",
      line: "행운의 힘이여, 길 잃은 자들을 인도하라!",
      gender: "여성",
      item: "마법봉",
      skill:
        "<행운의 숨소리>\n입김을 불어, 대상에게 행운을 전해줄 수 있다.\n행운의 별을 자신의 의지대로 조종할 수 있으며, 상황을 뒤집어 뜻밖의 행운을 불러올 수 있다.",
      like: "불운, 좁고 답답한 곳",
      hate: "다툼, 혼란한 상황",
      romi: "프린세스 트와일라잇",
      youtube: "https://www.youtube.com/embed/sMsqTpVfEEE",
    },
    {
      name: "빨리핑",
      img: "bbalri",
      seasonIdx: 2,
      type: "normal",
      line: "느림보처럼 여유로운 건 안돼, 빨리! 빨리빨리 서두르는 게 좋아, 빨리!",
      gender: "남성",
      item: "시계",
      skill: "<조급함의 시계>\n대상이 뭐든지 빨리빨리 서두르게 만든다.",
      like: "재촉하기, 바쁜 것",
      hate: "느긋함, 게으름",
      youtube: "https://www.youtube.com/embed/blCIDmHjsj4",
    },
    {
      name: "얌얌핑",
      img: "yamyam",
      seasonIdx: 2,
      type: "normal",
      line: "배부르면 모두모두 행복해지니까~ 얌얌!",
      gender: "여성",
      item: "포크, 접시",
      skill: "<식욕의 포크>\n대상이 음식을 계속 맛있게 먹도록 만든다.",
      like: "맛있는 음식, 같이 먹기",
      hate: "배고픔, 음식이 없을 때",
      youtube: "https://www.youtube.com/embed/IIm1QU8frMc",
    },
    {
      name: "뜨거핑",
      img: "ddgeo",
      seasonIdx: 2,
      type: "normal",
      line: "불타는 건 모두 꺼야 해! 뜨거!",
      gender: "여성",
      item: "소화기",
      skill:
        "<침착의 소화기>\n어떤 불이든 전부 끌 수 있으며,\n위기 상황일 때 물줄기의 반동으로 높이 날아올라 회피할 수 있다.",
      like: "불 끄기, 안전관리, 바비큐 요리",
      hate: "불, 뜨거운 것",
      youtube: "https://www.youtube.com/embed/bQEI61bXV_M",
    },
    {
      name: "삐뽀핑",
      img: "bbibbo",
      seasonIdx: 2,
      type: "normal",
      line: "환자 발견! 즉시 치료 개시! 삐뽀!",
      gender: "여성",
      item: "구급상자",
      skill:
        "<제압의 붕대>\n붕대로 상대방을 묶어 움직임을 막을 수 있다.\n간호핑을 불러내어 대상을 돌볼 수 있다.",
      like: "치료, 진료기록카드 모으기",
      hate: "‘엉터리 의사’ 라는 말",
      youtube: "https://www.youtube.com/embed/RzpB2DdCg5I",
    },
    {
      name: "간호핑",
      img: "ganho",
      seasonIdx: 2,
      type: "normal",
      line: "응급 환자 발생, 응급 환자 발생!",
      gender: "여성",
      item: "없음",
      skill: "없음",
      like: "?",
      hate: "?",
    },
    {
      name: "힘내핑",
      img: "himnae",
      seasonIdx: 2,
      type: "normal",
      line: "불꽃같은 응원으로~ 힘내라~ 힘내!",
      gender: "여성",
      item: "치어리딩 수술",
      skill: "<응원의 치어리딩>\n대상이 함께 응원을 하게 만든다.",
      like: "응원, 치어리딩",
      hate: "힘든 것, 포기",
      youtube: "https://www.youtube.com/embed/31iSahwHmFM",
    },
    {
      name: "고쳐핑",
      img: "gocheo",
      seasonIdx: 2,
      type: "normal",
      line: "다 고쳐놨으니 모두들 편해지겠지? 모두 나한테 맡겨! 고쳐!",
      gender: "남성",
      item: "렌치와 공구상자",
      skill:
        "<엉뚱의 공구상자>\n고장 난 물건을 고칠 수 있지만, 엉뚱하게 고쳐진다.",
      like: "고장 난 물건 수리하기, 공구들",
      hate: "고장 난 물건",
      youtube: "https://www.youtube.com/embed/gwAAtxRxYyI",
    },
    {
      name: "아라핑",
      img: "ara",
      seasonIdx: 2,
      type: "normal",
      line: "역시 난 천재야, 아라~ 이번엔 왠지 저기서 실험을 하고 싶은데? 아라!",
      gender: "여성",
      item: "플라스크와 마법 지팡이",
      skill:
        "<발명의 지팡이>\n마법으로 새로운 것을 발명해 내며\n다양한 마법의 물약을 만들어 낼 수 있다.",
      like: "실험하기, 발명품들",
      hate: "실험을 방해받는 것",
      youtube: "https://www.youtube.com/embed/7CK1WIePIoc",
    },
    {
      name: "패션핑",
      img: "fashion",
      seasonIdx: 2,
      type: "normal",
      line: "천재인 내가... 럭셔리한 옷으로 바꿔 줄게, 패숑!",
      gender: "여성",
      item: "줄자와 토르소",
      skill: "<코디의 토르소>\n옷을 만들어주거나 코디를 해줄 수 있다.",
      like: "옷 만들기, 코디해주기, 패션쇼",
      hate: "촌스러운 패션, 진부한 옷",
      youtube: "https://www.youtube.com/embed/8ZNEBOmP64s",
    },
    {
      name: "꼼딱핑",
      img: "ggomddak",
      seasonIdx: 2,
      type: "normal",
      line: "누가 날 불렀나, 꼼딱! 나는 정의를 수호하는 꼼딱핑이다, 꼼딱!",
      gender: "남성",
      item: "호루라기와 스쿠터, 성대모사용 확성기",
      skill: "<정의의 호루라기>\n대상이 두 손을 번쩍 들게 한다.",
      like: "순찰하기, 범인잡기, 성대모사",
      hate: "나쁜 짓 하는 녀석들",
      youtube: "https://www.youtube.com/embed/nzJomJ3XWwQ",
    },
    {
      name: "퐁당핑",
      img: "pongdang",
      seasonIdx: 2,
      type: "normal",
      line: "역시 노을은 여기서 보는 게 최고야, 퐁당!",
      gender: "여성",
      item: "소라껍데기",
      skill:
        "<변신의 소라껍데기>\n소라껍데기를 불어 수중 생물들이 자신을 돕게 할 수 있다.\n인어 꼬리를 만들어 수영할 수 있다.\n조개룸을 꺼내, 그 안에서 잠을 자거나, 배로 삼아 물 위를 이동할 수 있다.",
      like: "수영하기, 친구 핑크돌고래",
      hate: "그물, 억압받는 것",
      youtube: "https://www.youtube.com/embed/AdGGc9Yj_PQ",
    },
    {
      name: "파티핑",
      img: "party",
      seasonIdx: 2,
      type: "normal",
      line: "더 화려하고 신나는 파티를 하러 가야겠어, 파티~!",
      gender: "여성",
      item: "코끼리피리와 풍선",
      skill:
        "<파티의 피리>\n풍선을 타고 비행하여 이동할 수 있다.\n마법으로 특수한 안경을 씌워서,\n대상이 파티 현장에 있다고 생각하게 할 수 있다.",
      like: "화려한 파티, 놀기, 풍선",
      hate: "자기만 빼고 파티하는 것",
      youtube: "https://www.youtube.com/embed/XL8H4m3fzsg",
    },
    {
      name: "꾸며핑",
      img: "ggumyeo",
      seasonIdx: 2,
      type: "normal",
      line: "자, 너에게 딱 맞는 스타일을 찾아줄게, 꾸며~!",
      gender: "여성",
      item: "가위와 빗",
      skill: "<스타일의 가위>\n대상의 머리 스타일을 예쁘게 바꿀 수 있다.",
      like: "예쁜 머리 해주기, 빗질하기",
      hate: "못난 머리 스타일",
      youtube: "https://www.youtube.com/embed/pXo-UM38WIo",
    },
    {
      name: "삐짐핑",
      img: "bbijim",
      seasonIdx: 2,
      type: "normal",
      line: "힝! 오지 마! 오면... 나 삐질 꼬야![1] 에잇~! 삐짐!!",
      gender: "여성",
      item: "막대사탕",
      skill: "<토라짐의 막대사탕>\n대상이 토라지게 만들 수 있다.",
      like: "관심받기, 사랑받기",
      hate: "자신의 마음을 몰라주는 것",
      youtube: "https://www.youtube.com/embed/ujQ7p-C7NGc",
    },
    {
      name: "아아핑",
      img: "ahah",
      seasonIdx: 2,
      type: "normal",
      line: "잠깐! 내 이름은 아아핑이 아니라, 아아~♪핑이야! 아아~!",
      gender: "여성",
      item: "바이올린과 악보",
      skill:
        "<뮤지컬의 바이올린>\n바이올린 연주를 하면서 노래를 부르면 음파 공격을 할 수 있다.\n악보에 있는 음표에 닿으면,\n음표에 닿은 대상이 노래하듯이 말하게 만들 수 있다.",
      like: "노래 부르기, 바이올린 연주하기",
      hate: "노래를 제대로 부를 수 없는 것",
      youtube: "https://www.youtube.com/embed/7dmSAko2udM",
    },
    {
      name: "빙글핑",
      img: "bingle",
      seasonIdx: 2,
      type: "normal",
      line: "자~ 이제 나하고 트리플악셀을 뛰는 거야, 빙글!",
      gender: "여성",
      item: "팽이",
      skill:
        "<피겨 스케이팅의 팽이>\n팽이를 돌리면, 자신이 원하는 동작대로\n대상이 피겨 스케이트 동작을 따라할 수 있게 된다.",
      like: "피겨 스케이팅, 빙판",
      hate: "피겨 스케이팅에 진지하지 않은 것, 더운 것",
      youtube: "https://www.youtube.com/embed/XS3dt1qK1sg",
    },
  ],
  fourth: [
    {
      name: "베리 하츄핑",
      img: "berryhachu",
      seasonIdx: 3,
      type: "royal",
      line: "내 사랑을 듬뿍듬뿍 줄게~ 츄~♥",
      gender: "여성",
      item: "핸드벨",
      skill:
        "<사랑의 종소리> 핸드벨에서 딸기 타르트 모양 음표를 발산하여 상대를 교란시킨다.",
      like: "로미와 함께 있는 모든 순간, 생크림 딸기 케이크, 딸기",
      hate: "억지로 잠을 깨우는 것, 갑자기 깜짝 놀라게 하는 것, 신맛이 나는 모든 것",
      romi: "프린세스 베리하트",
      youtube: "https://www.youtube.com/embed/qBkELAwIlIA",
    },
    {
      name: "포실핑",
      img: "posil",
      seasonIdx: 3,
      type: "royal",
      line: "진정하고 그만해, 포실!",
      gender: "여성",
      item: "솜사탕 항아리와 스틱",
      skill:
        "<순수의 솜사탕>\n솜사탕 항아리를 스틱으로 휘저어서, 다양한 형체의 솜사탕을 발사한다.",
      like: "풍경 보기, 간식타임, 잠자기, 멍하게 생각에 잠기기, 초콜릿",
      hate: "맛없는 음식, 빨리빨리 하는 것, 거짓말",
      romi: "프린세스 스윗플로스",
      youtube: "https://www.youtube.com/embed/eqwoFyO4lzA",
    },
    {
      name: "말랑핑",
      img: "mallang",
      seasonIdx: 3,
      type: "royal",
      line: "훗! 내가 말랑말랑 젤리 티니핑이라는 걸 잊은 모양이군!",
      gender: "여성",
      item: "줄 달린 탱탱볼",
      skill:
        "<재미의 젤리볼>\n탱탱볼을 통통 튕겨서 대상을 공격하거나, 탈 수 있고, 탱탱볼을 어딘가에 찰싹 붙게 만들어 활용한다.",
      like: "놀이, 운동, 새로운 것",
      hate: "지루한 분위기",
      romi: "프린세스 젤리스틴",
      youtube: "https://www.youtube.com/embed/fjnzsML3bNw",
    },
    {
      name: "샤샤핑",
      img: "shasha",
      seasonIdx: 3,
      type: "royal",
      line: "난 차가운 걸 좋아하는 아이스크림의 요정이야, 샤샤~",
      gender: "여성",
      item: "아이스크림 콘 모자, 아이스크림 요정들",
      skill:
        "<긍정의 샤베트>\n아이스크림 요정들로 공격, 서포트, 방어 등 다양하게 활용한다.",
      like: "음식 만들어서 나눠주기, 이야기 들어주기, 밝은 분위기",
      hate: "좌절, 절망, 포기, 어두운 분위기",
      romi: "프린세스 샤베티나",
      youtube: "https://www.youtube.com/embed/6NC6hPAM8Ew",
    },
    {
      name: "새콤핑",
      img: "saekom",
      seasonIdx: 3,
      type: "legend",
      line: "새콤하게 머무는 슈가매직의 힘이여! (달콤핑과 함께) 동요를 멈추고 제자리로 돌아가라!",
      gender: "여성",
      item: "새콤 요술봉",
      skill: "<상큼함의 슈가매직>",
      like: "새콤한 것, 쪽지 쓰기, 케이크 만들기",
      hate: "새콤함을 싫어하는 사람",
      romi: "프린세스 하모니어스",
      youtube: "https://www.youtube.com/embed/Ros3gi7DlGQ",
    },
    {
      name: "달콤핑",
      img: "dalkom",
      seasonIdx: 3,
      type: "legend",
      line: "달콤하게 감도는 슈가매직의 힘이여! (새콤핑과 함께) 동요를 멈추고 제자리로 돌아가라!",
      gender: "여성",
      item: "달콤 요술봉",
      skill: "<달달함의 슈가매직>",
      like: "달콤한 것, 쪽지 쓰기, 케이크 만들기",
      hate: "달콤함을 싫어하는 사람",
      romi: "프린세스 하모니어스",
      youtube: "https://www.youtube.com/embed/Ros3gi7DlGQ",
    },
    {
      name: "뿌뿌핑",
      img: "bbubbu",
      seasonIdx: 3,
      type: "villain",
      line: "이건 영원히 내 거야! 아무도 손댈 수 없어! 뿌뿌!",
      gender: "남성",
      item: "풍선껌 디스펜서",
      skill:
        "풍선껌을 활용한 다양한 마법(공격, 회피, 이동)\n스스로를 풍선껌처럼 부풀릴 수 있고,\n특정 부분(ex.귀)만 부풀릴 수도 있다.",
      like: "골탕 먹이기, 장난치기, 남 속이기, 강해지는 것, 외롭지 않은 것",
      hate: "자기만 빼고 즐거운 것, 자기 것을 빼앗기는 것, 외로움, 자기만 빼고 친하게 지내는 친구들, 고독감",
      youtube: "https://www.youtube.com/embed/-eE-r2yKB5k",
    },
    {
      name: "캔디핑",
      img: "candy",
      seasonIdx: 3,
      type: "normal",
      line: "너희는 역시 달콤한 말이 필요하겠어! 캔디 캔디 내 귀에 캔디!",
      gender: "여성",
      item: "사탕 바구니",
      skill: "달콤한 말로 칭찬하게 만든다.",
      like: "칭찬하기, 달콤한 말",
      hate: "싸움, 상처 주는 말, 부정적인 말",
      youtube: "https://www.youtube.com/embed/28acd5YQ4Rc",
    },
    {
      name: "머랭핑",
      img: "meorang",
      seasonIdx: 3,
      type: "normal",
      line: "으... 끔찍해. 못 봐주겠어! 빨리 장식해야지!",
      gender: "여성",
      item: "거품기",
      skill:
        "머랭으로 뭐든지 장식해 준다.\n단단한 머랭 반죽처럼, 본인은 벽타기를 해도 떨어지지 않는다.",
      like: "머랭 장식하기, 화려하고 예쁜 것",
      hate: "수수한 것, 어둡고 칙칙한 것",
      youtube: "https://www.youtube.com/embed/i77Ay4UqbWM",
    },
    {
      name: "샌드핑",
      img: "sand",
      seasonIdx: 3,
      type: "normal",
      line: "빈 곳이 있으면 모조리 채워줄거야, 샌드!",
      gender: "여성",
      item: "스패츌러",
      skill: "뭐든 빈 곳에 크림을 채워준다.",
      like: "크림으로 샌드하기, 빈틈 찾아 채우기",
      hate: "샌드쿠키를 반으로 갈라 먹는 것",
      youtube: "https://www.youtube.com/embed/cbv0_oJZ1W0",
    },
    {
      name: "또너핑",
      img: "ddoneo",
      seasonIdx: 3,
      type: "normal",
      line: "엣헴, 나도 이제 로열티니핑이야, 또너!”",
      gender: "여성",
      item: "도넛링",
      skill: "대상에 동그란 구멍을 낸다.",
      like: "로미, 예쁨 받기, 칭찬, 그림 그리기, 구멍 뚫기",
      hate: "어린애 취급받는 것, 무시당하는 것",
      youtube: "https://www.youtube.com/embed/bYCajBUlhMc",
    },
    {
      name: "와플핑",
      img: "waffle",
      seasonIdx: 3,
      type: "normal",
      line: "납작해져라, 와플!",
      gender: "남성",
      item: "심벌즈",
      skill: "뭐든지 납작하게 만든다.",
      like: "납작하게 만들기, 장난치기",
      hate: "참기, 가만히 멈춰있기",
      youtube: "https://www.youtube.com/embed/3Qsob2VF8BI",
    },
    {
      name: "롤리핑",
      img: "lolli",
      seasonIdx: 3,
      type: "normal",
      line: "빙빙 돌아라, 예쁘게 롤리!",
      gender: "여성",
      item: "바람개비",
      skill: "뭐든지 빙글빙글 회전시킨다.",
      like: "빙빙 돌아가는 것, 회전시키기, 루카",
      hate: "친구가 슬픈 것, 정지된 사물",
      youtube: "https://www.youtube.com/embed/LFqEPcYFDFk",
    },
    {
      name: "마카핑",
      img: "maca",
      seasonIdx: 3,
      type: "normal",
      line: "알록달록, 마카!”",
      gender: "여성",
      item: "짤주머니",
      skill: "대상의 색상을 바꿀 수 있다.",
      like: "알록달록한 것, 색깔 바꾸기",
      hate: "단조로움, 어둡고 칙칙한 색",
      youtube: "https://www.youtube.com/embed/cUPHpvLEGqk",
    },
    {
      name: "핫케핑",
      img: "hotca",
      seasonIdx: 3,
      type: "normal",
      line: "차곡차곡 쌓아올려, 핫케!",
      gender: "여성",
      item: "마법 프라이팬",
      skill: "뭐든지 차곡차곡 쌓아올린다.",
      like: "쌓기, 남을 돕는 것, 노력하는 사람",
      hate: "마구잡이로 흩어져 있는 것",
      youtube: "https://www.youtube.com/embed/ItZxr-pjnNc",
    },
    {
      name: "커핑",
      img: "keo",
      seasonIdx: 3,
      type: "normal",
      line: "",
      gender: "남성",
      item: "유모차, 컵케이크 바구니",
      skill:
        "대상이 아기처럼 행동하게 한다.(대상의 입에 쪽쪽이가 물려진다.)\n울면 자신의 몸이 거대해지고, 그치면 다시 원래대로 돌아온다.\n위험에 처했을 때, 유모차가 자신들을 구해주러 온다.",
      like: "쪽쪽이, 둘이 함께 있기, 술래잡기, 우스꽝스러운 상황, 또너핑",
      hate: "혼나는 것, 쪽쪽이를 빼앗기는 것, 배고픈 것, 꾸중을 듣는 것",
      youtube: "https://www.youtube.com/embed/D7XhvPmBXlQ",
    },
    {
      name: "머핑",
      img: "meo",
      seasonIdx: 3,
      type: "normal",
      line: "",
      gender: "여성",
      item: "유모차, 컵케이크 바구니",
      skill:
        "대상이 아기처럼 행동하게 한다.(대상의 입에 쪽쪽이가 물려진다.)\n울면 자신의 몸이 거대해지고, 그치면 다시 원래대로 돌아온다.\n위험에 처했을 때, 유모차가 자신들을 구해주러 온다.",
      like: "쪽쪽이, 둘이 함께 있기, 술래잡기, 우스꽝스러운 상황, 또너핑",
      hate: "혼나는 것, 쪽쪽이를 빼앗기는 것, 배고픈 것, 꾸중을 듣는 것",
      youtube: "https://www.youtube.com/embed/D7XhvPmBXlQ",
    },
    {
      name: "요거핑",
      img: "yogeo",
      seasonIdx: 3,
      type: "normal",
      line: "하품이야, 얘들아! 잘 자요~를레이, 요거!",
      gender: "여성",
      item: "나무스푼, 요거트양 2마리(산딸기 & 블루베리)",
      skill: "요들을 부르면서 마법 스푼과 요거트양들로 대상을 푹 잠들게 한다.",
      like: "푹 재워주는 것, 요거트양들, 요거트 만들어 나눠주기, 요들송 부르기",
      hate: "잠을 안 자는 사람, 잠의 중요성을 모르는 사람",
      youtube: "https://www.youtube.com/embed/ujg-TEKCb0s",
    },
    {
      name: "눈꽃핑",
      img: "nunggot",
      seasonIdx: 3,
      type: "normal",
      line: "하얀 눈아~ 내려라, 눈꽃!",
      gender: "여성",
      item: "찹쌀떡 눈썰매",
      skill: "눈이 내리게 하는 등\n눈이나 얼음과 관련된 마법을 쓸 수 있다.",
      like: "눈썰매 타기, 샤샤핑, 친구 사귀기",
      hate: "돌발상황, 친구를 아프게 하는 것, 조절이 서툰 마법능력",
      youtube: "https://www.youtube.com/embed/4hhnV8YZht8",
    },
    {
      name: "푸딩핑",
      img: "pudding",
      seasonIdx: 3,
      type: "normal",
      line: "신나게 춤추면 푸딩도 더, 더 맛있어져~!",
      gender: "여성",
      item: "푸딩 모양의 텀블러",
      skill:
        "대상이 작은 일에도 충격을 받게 할 수 있다.\n신나는 음악을 들으면 주변의 모두가 푸딩댄스를 추게 한다.",
      like: "신나는 음악, 춤추기, 푸딩 만들어 나눠주기",
      hate: "비웃음 받는 것",
      youtube: "https://www.youtube.com/embed/HI_cyB_sJvQ",
    },
    {
      name: "멜로핑",
      img: "mello",
      seasonIdx: 3,
      type: "normal",
      line: "딱딱한 건 모두 폭신하게 만들 거야, 멜로!",
      gender: "여성",
      item: "마시멜롱",
      skill: "대상을 폭신하게 만든다.\n마시멜롱을 자유자재로 활용한다.",
      like: "폭신한 것, 상냥한 사람",
      hate: "딱딱한 것, 높은 곳",
      youtube: "https://www.youtube.com/embed/FPa5LYxbB0w",
    },
    {
      name: "쪼꼬핑",
      img: "zzoggo",
      seasonIdx: 3,
      type: "normal",
      line: "싸우면 안 돼, 쪼꼬! 사이좋게~ 쪼꼬!",
      gender: "여성",
      item: "모자",
      skill: "누구든 초코 모자를 씌워 사이좋은 친구로 만든다.",
      like: "사이좋은 친구들, 다정한 사람",
      hate: "싸우는 친구들, 미워하는 것",
      youtube: "https://www.youtube.com/embed/d_hg9VRR3I0",
    },
  ],
  fifth: [
    {
      name: "스타 하츄핑",
      img: "starhachu",
      seasonIdx: 4,
      type: "royal",
      line: "내 사랑을 듬뿍듬뿍 줄게~ 츄~♥",
      gender: "여성",
      item: "글로우 퍼프",
      skill: "<사랑의 별가루>",
      like: "생크림 딸기 케이크, 딸기",
      hate: "억지로 잠을 깨우는 것, 갑자기 깜짝 놀라게 하는 것, 신맛이 나는 모든 것",
      romi: "프린세스 브라잇하트",
    },
    {
      name: "빛나핑",
      img: "bitna",
      seasonIdx: 4,
      type: "royal",
      line: "",
      gender: "여성",
      item: "플루트",
      skill: "<치유의 멜로디>",
      like: "?",
      hate: "?",
      romi: "프린세스 스타라이트",
    },
    {
      name: "초롱핑",
      img: "chorong",
      seasonIdx: 4,
      type: "royal",
      line: "",
      gender: "여성",
      item: "별 머리핀",
      skill: "<소망의 작은 별>",
      like: "?",
      hate: "?",
      romi: "프린세스 글램스타",
    },
    {
      name: "빤짝핑",
      img: "bbanzzak",
      seasonIdx: 4,
      type: "royal",
      line: "",
      gender: "여성",
      item: "솜인형",
      skill: "<밝음의 솜인형>",
      like: "?",
      hate: "?",
      romi: "프린세스 루나 샤인",
    },
  ],
};
